import { validateEnv } from '../config/env.js';

// Validate environment variables at module load
const env = validateEnv();

export const constants = {
  NODE_ENV: env.NODE_ENV,
  
  TWITTER_CONSUMER_KEY: env.TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET: env.TWITTER_CONSUMER_SECRET,
  TWITTER_ACCESS_TOKEN: env.TWITTER_ACCESS_TOKEN,
  TWITTER_ACCESS_SECRET: env.TWITTER_ACCESS_SECRET,
  TWITTER_CALLBACK_URL: env.TWITTER_CALLBACK_URL,

  SESSION_SECRET: env.SESSION_SECRET,
  FRONTEND_URL: env.FRONTEND_URL,

  JWT_SECRET: env.JWT_SECRET,
  JWT_EXPIRES_IN: env.JWT_EXPIRES_IN,

  MONGODB_URI: env.MONGODB_URI,
  MONGODB_NAME_DATABASE: env.MONGODB_NAME_DATABASE,

  PRIVY_APP_ID: env.PRIVY_APP_ID,
  PRIVY_APP_SECRET: env.PRIVY_APP_SECRET,

  LLM_API_KEY: env.LLM_API_KEY,
  LLM_MODEL: env.LLM_MODEL,

  PORT: env.PORT,
};